import {
  pgTable,
  pgEnum,
  uuid,
  text,
  integer,
  smallint,
  boolean,
  numeric,
  timestamp,
  date,
  jsonb,
} from 'drizzle-orm/pg-core'

// ============================================================
// FleetFlow Premium — Drizzle schema
//
// Hand-written, NOT generated by `drizzle-kit pull` — that tool crashes on
// this database due to an unrelated drizzle-kit bug while parsing check
// constraints (a long-standing, still-open issue: "Cannot read properties
// of undefined (reading 'replace')" — reported against several drizzle-kit
// versions). Supabase's own Drizzle quickstart docs recommend hand-authoring
// the schema file anyway rather than relying on introspection.
//
// This file was built by cross-referencing supabase/schema.sql + every
// supabase/patch_*.sql file against a live dump of information_schema.columns
// and pg_enum taken directly from production on 2026-07-09, so it reflects
// the database exactly as it actually exists — not just what the patch
// files describe (some columns were relaxed/added slightly differently than
// documented, e.g. several bookings NOT NULL constraints were dropped later
// for draft support).
//
// ⚠️ Do NOT run `drizzle-kit push` or `drizzle-kit generate` against this
// file without carefully reviewing the diff first. This schema exists
// purely so application code gets type-safe query building against the
// *existing* database — it is not the source of truth for schema changes.
// supabase/patch_*.sql files (applied by hand via the Supabase SQL Editor)
// remain the source of truth for schema changes; update this file to match
// afterward.
//
// auth.* tables are managed entirely by Supabase Auth and are intentionally
// not modeled here — profiles.id just stores that table's UUID directly.
//
// email_verifications table still exists in the DB but is intentionally
// omitted here — the email verification feature was fully removed from the
// app (see git history), so nothing should query this table going forward.
// ============================================================

// ─────────────────────────────────────────────────────────────
// ENUMS
// ─────────────────────────────────────────────────────────────
export const userRoleEnum = pgEnum('user_role', ['admin', 'staff', 'manager', 'finance'])
export const bookingStatusEnum = pgEnum('booking_status', ['pending', 'quoted', 'approved', 'completed', 'cancelled'])
export const vehicleTypeEnum = pgEnum('vehicle_type', ['sedan', 'suv', 'van', 'minibus', 'luxury', 'pickup'])
export const approvalActionEnum = pgEnum('approval_action', ['approved', 'rejected', 'revision_requested'])
// NOTE: app code inserts notifications with type 'new_booking' in two places
// (app/api/public/bookings/route.ts, app/api/public/bookings/[reference]/route.ts)
// but 'new_booking' has never actually been a valid value of this enum in
// the live database — confirmed via pg_enum on 2026-07-09. Those inserts
// have been silently failing in production ever since (supabase-js doesn't
// throw on DB errors unless the caller checks `.error`, and neither call
// site does). Flagged to Tiffany; deliberately not fixed here since it's a
// pre-existing bug unrelated to this PostgREST-bypass migration. Fix is a
// one-line `ALTER TYPE notification_type ADD VALUE 'new_booking';` whenever
// she wants it applied — after that, add 'new_booking' to this list too.
export const notificationTypeEnum = pgEnum('notification_type', ['new_request', 'approval_needed', 'approved', 'payment_due', 'system'])

// ─────────────────────────────────────────────────────────────
// PROFILES (extends Supabase auth.users — id is that table's PK)
// ─────────────────────────────────────────────────────────────
export const profiles = pgTable('profiles', {
  id: uuid('id').primaryKey(),
  email: text('email').notNull(),
  fullName: text('full_name').notNull().default(''),
  role: userRoleEnum('role').notNull().default('staff'),
  avatarUrl: text('avatar_url'),
  department: text('department'),
  phone: text('phone'),
  isActive: boolean('is_active').notNull().default(true),
  lastLoginAt: timestamp('last_login_at', { withTimezone: true }),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
})

// ─────────────────────────────────────────────────────────────
// SUPPLIERS
// ─────────────────────────────────────────────────────────────
export const suppliers = pgTable('suppliers', {
  id: uuid('id').primaryKey().defaultRandom(),
  companyName: text('company_name').notNull(),
  contactPerson: text('contact_person').notNull(),
  phone: text('phone').notNull(),
  email: text('email').notNull(),
  address: text('address'),
  vehicleTypes: vehicleTypeEnum('vehicle_types').array().notNull().default([]),
  baseRateUsd: numeric('base_rate_usd', { precision: 10, scale: 2 }),
  rating: numeric('rating', { precision: 2, scale: 1 }).default('0'),
  totalBookings: integer('total_bookings').notNull().default(0),
  isAvailable: boolean('is_available').notNull().default(true),
  isPreferred: boolean('is_preferred').notNull().default(false),
  notes: text('notes'),
  createdBy: uuid('created_by'),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
})

// ─────────────────────────────────────────────────────────────
// DRIVERS
// ─────────────────────────────────────────────────────────────
export const drivers = pgTable('drivers', {
  id: uuid('id').primaryKey().defaultRandom(),
  fullName: text('full_name').notNull(),
  phone: text('phone').notNull(),
  licenseNumber: text('license_number').notNull(),
  licenseExpiry: date('license_expiry'),
  vehicleTypes: vehicleTypeEnum('vehicle_types').array().notNull().default([]),
  isAvailable: boolean('is_available').notNull().default(true),
  assignedSupplierId: uuid('assigned_supplier_id'),
  notes: text('notes'),
  createdBy: uuid('created_by'),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
})

// ─────────────────────────────────────────────────────────────
// BOOKINGS
// ─────────────────────────────────────────────────────────────
export const bookings = pgTable('bookings', {
  id: uuid('id').primaryKey().defaultRandom(),
  referenceNumber: text('reference_number').notNull(),
  guestName: text('guest_name'),
  guestNationality: text('guest_nationality'),
  guestCount: integer('guest_count').notNull().default(1),
  pickupDatetime: timestamp('pickup_datetime', { withTimezone: true }),
  dropoffDatetime: timestamp('dropoff_datetime', { withTimezone: true }),
  pickupLocation: text('pickup_location'),
  dropoffLocation: text('dropoff_location'),
  vehicleType: vehicleTypeEnum('vehicle_type').notNull().default('sedan'),
  driverRequired: boolean('driver_required').notNull().default(false),
  budgetUsd: numeric('budget_usd', { precision: 10, scale: 2 }),
  finalCostUsd: numeric('final_cost_usd', { precision: 10, scale: 2 }),
  status: bookingStatusEnum('status').notNull().default('pending'),
  notes: text('notes'),
  specialRequests: text('special_requests'),
  assignedSupplier: uuid('assigned_supplier'),
  createdBy: uuid('created_by'),
  approvedBy: uuid('approved_by'),
  approvedAt: timestamp('approved_at', { withTimezone: true }),
  completedAt: timestamp('completed_at', { withTimezone: true }),
  cancelledAt: timestamp('cancelled_at', { withTimezone: true }),
  cancellationReason: text('cancellation_reason'),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
  guestEmail: text('guest_email'),
  guestPhone: text('guest_phone'),
  guestLineId: text('guest_line_id'),
  driverId: uuid('driver_id'),
  vehiclePlate: text('vehicle_plate'),
  vehicleModel: text('vehicle_model'),
  modificationStatus: text('modification_status'),
  modificationPickupDatetime: timestamp('modification_pickup_datetime', { withTimezone: true }),
  modificationPickupLocation: text('modification_pickup_location'),
  modificationDropoffLocation: text('modification_dropoff_location'),
  modificationNotes: text('modification_notes'),
  modificationRequestedAt: timestamp('modification_requested_at', { withTimezone: true }),
  isDraft: boolean('is_draft').notNull().default(false),
})

// ─────────────────────────────────────────────────────────────
// QUOTES
// ─────────────────────────────────────────────────────────────
export const quotes = pgTable('quotes', {
  id: uuid('id').primaryKey().defaultRandom(),
  bookingId: uuid('booking_id').notNull(),
  supplierId: uuid('supplier_id').notNull(),
  amountUsd: numeric('amount_usd', { precision: 10, scale: 2 }).notNull(),
  includesDriver: boolean('includes_driver').notNull().default(false),
  vehicleModel: text('vehicle_model'),
  estimatedDurationHours: numeric('estimated_duration_hours', { precision: 5, scale: 2 }),
  validUntil: timestamp('valid_until', { withTimezone: true }),
  notes: text('notes'),
  isSelected: boolean('is_selected').notNull().default(false),
  createdBy: uuid('created_by'),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  invoicePath: text('invoice_path'),
})

// ─────────────────────────────────────────────────────────────
// APPROVALS
// ─────────────────────────────────────────────────────────────
export const approvals = pgTable('approvals', {
  id: uuid('id').primaryKey().defaultRandom(),
  bookingId: uuid('booking_id').notNull(),
  reviewerId: uuid('reviewer_id').notNull(),
  action: approvalActionEnum('action').notNull(),
  comments: text('comments'),
  revisionNotes: text('revision_notes'),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
})

// ─────────────────────────────────────────────────────────────
// NOTIFICATIONS
// ─────────────────────────────────────────────────────────────
export const notifications = pgTable('notifications', {
  id: uuid('id').primaryKey().defaultRandom(),
  userId: uuid('user_id').notNull(),
  type: notificationTypeEnum('type').notNull(),
  title: text('title').notNull(),
  message: text('message').notNull(),
  bookingId: uuid('booking_id'),
  isRead: boolean('is_read').notNull().default(false),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
})

// ─────────────────────────────────────────────────────────────
// REPORTS CACHE
// ─────────────────────────────────────────────────────────────
export const reportsCache = pgTable('reports_cache', {
  id: uuid('id').primaryKey().defaultRandom(),
  reportKey: text('report_key').notNull(),
  data: jsonb('data').notNull(),
  generatedAt: timestamp('generated_at', { withTimezone: true }).notNull().defaultNow(),
  expiresAt: timestamp('expires_at', { withTimezone: true }).notNull(),
})

// ─────────────────────────────────────────────────────────────
// AUDIT LOG
// ─────────────────────────────────────────────────────────────
export const auditLog = pgTable('audit_log', {
  id: uuid('id').primaryKey().defaultRandom(),
  bookingId: uuid('booking_id'),
  actorId: uuid('actor_id'),
  actorName: text('actor_name'),
  action: text('action').notNull(),
  field: text('field'),
  oldValue: text('old_value'),
  newValue: text('new_value'),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  note: text('note'),
})

// ─────────────────────────────────────────────────────────────
// FEEDBACK
// ─────────────────────────────────────────────────────────────
export const feedback = pgTable('feedback', {
  id: uuid('id').primaryKey().defaultRandom(),
  bookingId: uuid('booking_id').notNull(),
  referenceNumber: text('reference_number').notNull(),
  rating: smallint('rating').notNull(),
  comment: text('comment'),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
})
